name: fababean_iou_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - openpyxl
  - opencv
  - pillow
  - matplotlib
  - tqdm
  - pyyaml
  - scipy
  - pytorch
  - torchvision
  - pip:
      - pycocotools
